import { Box } from "@mui/material";
import Head from "next/head";
import Image from "next/image";
import LandingPage from "../components/Home/LandingPage";
// import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Employee Management Application</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <LandingPage />
    </div>
  );
}
